export const functionArrayProperties =  [
    "abs", "absNative", 1, "number",
    "acos", "acosNative", 1, "coseno",
    "acosh", "acoshNative", 1, "hyperbolic coseno",
    "asin", "asinNative", 1, "sine",
    "asinh", "asinhNative", 1, "hyperbolic sine",
    "atan", "atanNative", 1, "tangent",
    "atan2", "atan2Native", 2, "opossite,adjacent",
    "atanh", "atanhNative", 1, "hyperbolic tangent",
    "cbrt", "cbrtNative", 1, "number",
    "ceil", "ceilNative", 1, "number",
    "cos", "cosNative", 1, "angle",
    "cosh", "coshNative", 1, "angle",
    "exp", "expNative", 1, "number",
    "expm1", "expm1Native", 1, " ",
    "floor", "floorNative", 1, "number",
    "hypot2", "hypot2Native", 2, "first point,second point",
    "ln", "lnNative", 1, " ",
    "log", "logNative", 1, " ",
    "ln1p", "ln1pNative", 1, " ",
    "log2", "log2Native", 1, " ",
    "max2", "max2Native", 2, "first number,second number",
    "min2", "min2Native", 2, "first number,second number",
    "pow", "powNative", 1, " ",
     
    "round", "roundNative", 1, "number",
    "sign", "signNative", 1, "number",
    "sin", "sinNative", 1, "angle",
    "sinh", "sinhNative", 1, "angle",
    "sqrt", "sqrtNative", 1, "number",
    "tan", "tanNative", 1, "angle",
    "tanh", "tanhNative", 1, " ",
    "trunc", "truncNative", 1, "number",
    "degToRad", "degToRadNative", 1, "angle in degrees",
    "radToDeg", "radToDegNative", 1, "angle in radians",
    "limitXY", "CartesianLimits", 4, "xMin, xMax, yMin, yMax"

];